[package]
name = "cppm-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clap = { version = "3.1.8", features = ["derive"] }
nalgebra = "0.30.1"
num-traits = "0.2"
average = "0.13.1"
itertools = "0.10.3"
approx = "0.5.1"